name: valorant_wiki_app
description: Valorant Wiki Application
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_vector_icons: ^2.0.0
  # Responsive
  flutter_screenutil: ^5.7.0


  # Network
  http: ^0.13.6

  # Shimmer
  shimmer: ^3.0.0

  # Permissions
  permission_handler: ^10.4.3

  # Cache
  flutter_cache_manager: ^3.3.1
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3

  # Photo View
  photo_view: ^0.14.0

  # Connectivity
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1

  # Localization
  easy_localization: ^3.0.2

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lang/

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/archivo/Archivo-Italic-VariableFont_wdth,wght.ttf
    - family: Valorant
      fonts:
        - asset: assets/fonts/valorant/Valorant.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Italic-VariableFont_wght.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
