name: valorant_wiki_app
description: Valorant Wiki Application
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.7.0
  flutter_native_splash: ^2.2.19
  flutter_vector_icons: ^2.0.0
  http: ^0.13.6
  shimmer: ^3.0.0

  # Localization
  easy_localization: ^3.0.2

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/red_typo_ic.png
  color_dark: "#0F1923"
  image_dark: assets/images/red_typo_ic.png

  android_12:
    image: assets/images/red_typo_ic.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/red_typo_ic.png
    icon_background_color_dark: "#0F1923"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lang/

  fonts:
    - family: Valorant
      fonts:
        - asset: assets/fonts/valorant/Valorant-Font.ttf
    - family: Archivo
      fonts:
        - asset: assets/fonts/archivo/Archivo-Italic-VariableFont_wdth,wght.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Italic-VariableFont_wght.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
